# Generated by Django 4.2.11 on 2024-05-27 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("big", models.CharField(max_length=100)),
                ("detail", models.CharField(max_length=100)),
                ("url", models.URLField()),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=20)),
                ("date", models.CharField(max_length=20)),
            ],
        ),
    ]
