# Generated by Django 5.0.6 on 2024-05-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('big', models.CharField(max_length=100)),
                ('detail', models.CharField(max_length=100)),
                ('url', models.URLField()),
            ],
        ),
    ]
