# Generated by Django 4.2.11 on 2024-05-27 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notice", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="author",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="date",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
